FROM ubuntu:20.04

#作業ディレクトリの準備
RUN cd ~
RUN mkdir jupyter
RUN cd jupyter
RUN mkdir src
RUN mkdir datas
RUN cd

#初期処理
RUN apt -y update
RUN apt-get install -y tzdata

#キーボード設定
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y  -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" keyboard-configuration


#Python環境のインストール
RUN apt -y install python-is-python3 python3-dev python3-pip python3-setuptools python3-venv

#jupyterなどのインストール
RUN apt -y update
RUN apt -y install python-is-python3 python3-dev python3-pip python3-setuptools python3-venv
RUN pip3 uninstall ptyprocess sniffio terminado tornado jupyterlab jupyter jupyter-console jupytext nteract_on_jupyter spyder
RUN apt -y install jupyter jupyter-qtconsole spyder3
RUN apt -y install python3-ptyprocess python3-sniffio python3-terminado python3-tornado 
RUN pip3 install -U jupyterlab nteract_on_jupyter

#jupyterのデバッガをインストール
RUN pip install xeus-python
RUN ipython kernel install --user --name=xeus-python --display-name=xeus-py

#jupyterの拡張機能をインストール
RUN pip install jupyterlab_tabnine
RUN pip install jupyterlab-language-pack-ja-JP
RUN pip install jupyterlab_code_formatter
RUN pip install jupytext

#dlibをビルドするツールのインストール
RUN apt -y update
RUN apt -y install git cmake cmake-curses-gui cmake-gui curl wget p7zip-full
RUN apt -y update
RUN apt -y install build-essential gcc g++ make libtool texinfo dpkg-dev pkg-config

#Pythonのライブラリをインストール
ENV PIP_DIR="/py_libs/"
ADD py_libs/ $PIP_DIR
WORKDIR $PIP_DIR
RUN pip install -r requirements.txt

#コンテナ起動時のデフォルトのコマンドを追記
CMD ["/bin/bash"]